/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackNavBar: typeof import('./src/components/BackNavBar.vue')['default']
    ChatIcon: typeof import('./src/components/icons/ChatIcon.vue')['default']
    DisappearingImageMessage: typeof import('./src/components/messages/DisappearingImageMessage.vue')['default']
    DislikeIcon: typeof import('./src/components/icons/DislikeIcon.vue')['default']
    FemaleIcon: typeof import('./src/components/icons/FemaleIcon.vue')['default']
    ImageMessage: typeof import('./src/components/messages/ImageMessage.vue')['default']
    LikeIcon: typeof import('./src/components/icons/LikeIcon.vue')['default']
    LoadingCard: typeof import('./src/components/LoadingCard.vue')['default']
    MaleIcon: typeof import('./src/components/icons/MaleIcon.vue')['default']
    Message: typeof import('./src/components/messages/Message.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostCardHeader: typeof import('./src/components/PostCardHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextMessage: typeof import('./src/components/messages/TextMessage.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSpace: typeof import('vant/es')['Space']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
