import './assets/styles/base.scss'
import 'virtual:svg-icons-register'
import 'vant/es/dialog/style'
import 'vant/es/notify/style'

import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'

// import { TUIComponents, TUICore, genTestUserSig } from './TUIKit'
// import TUICallKit
// import { TUICallKit } from '@tencentcloud/call-uikit-vue'

// const SDKAppID = 1600009914 // Your SDKAppID
// const secretKey = 'd82b484df8d55fc6077400a56a4a42a5ef7ce2a53ee05777e7b416f6ee6d0c79' //Your secretKey
// const userID = 'admin' // User ID

// init TUIKit
// const TUIKit = TUICore.init({
//   SDKAppID
// })
// TUIKit add TUIComponents
// TUIKit.use(TUIComponents)
// TUIKit add TUICallKit
// TUIKit.use(TUICallKit)

// login TUIKit
// TUIKit.login({
//   userID: userID,
//   userSig: genTestUserSig({
//     SDKAppID,
//     secretKey,
//     userID
//   }).userSig // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
// })

const app = createApp(App)

app.use(createPinia())
app.use(router)
// app.use(TUIKit)

app.mount('#app')
